### ISSUE TITLE
FireTowerPlugin的protocol判断有误

### ISSUE THREAD

**Issue by loinky** [holdno/gopherCronFE#17]
![20240428113212](https://github.com/holdno/gopherCronFE/assets/63998162/6a1a5bdb-962d-486a-9c89-f71f33aeb55d)

[Location: protocol property](https://developer.mozilla.org/en-US/docs/Web/API/Location/protocol)

The protocol property of the [Location](https://developer.mozilla.org/en-US/docs/Web/API/Location) interface is a string representing the protocol scheme of the URL, including the final ':'.

**Comment by holdno** [comment]
fixed in latest master
